spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lifemind?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: Zsql2312728

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    # ????sql?dev???pro?????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??????
    map-underscore-to-camel-case: true
    # map ??value?null???
    call-setters-on-nulls: true
  mapper-locations: classpath*:com/lifemind/mapper/xml/*.xml

#  type-aliases-package: com.example.pojo
server:
  port: 8081
