spring:
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 500MB
  #      配置最大的请求数据量 和文件大小
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: *
    username: *
    password: *

  mail:
    # 邮件服务地址，可以配置其他邮箱服务地址，例如：smtp.qq.com
    default-encoding: UTF-8
    host: *
    username: *
    password:*
    properties:
      mail:
        smtp:
          auth: true
          #如果是用 SSL 方式，需要配置如下属性
          starttls:
            enable: true
            required: true
    port: 25

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    # ????sql?dev???pro?????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??????
    map-underscore-to-camel-case: true
    # map ??value?null???
    call-setters-on-nulls: true
  mapper-locations: classpath*:mapper/xml/*.xml

#  type-aliases-package: com.example.pojo
server:
  port: *
file-save-path: *
